name: 'TestifyAI Agent'
description: 'An AI agent that automatically writes tests for your code.'
author: 'khanzzirfan'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'radio'
  color: 'blue'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'sample input'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
